"""Initial tables for Uniswap monitoring

Revision ID: 001
Revises: 
Create Date: 2024-12-02 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create pools table
    op.create_table('pools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=42), nullable=False),
        sa.Column('token0', sa.String(length=42), nullable=False),
        sa.Column('token1', sa.String(length=42), nullable=False),
        sa.Column('pool_type', sa.String(length=10), nullable=False),
        sa.Column('fee', sa.Integer(), nullable=True),
        sa.Column('created_at_block', sa.BigInteger(), nullable=False),
        sa.Column('created_at_tx', sa.String(length=66), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('token0_symbol', sa.String(length=20), nullable=True),
        sa.Column('token1_symbol', sa.String(length=20), nullable=True),
        sa.Column('token0_decimals', sa.Integer(), nullable=True),
        sa.Column('token1_decimals', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_address'), 'pools', ['address'], unique=True)
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    
    # Create trade_events table
    op.create_table('trade_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_address', sa.String(length=42), nullable=False),
        sa.Column('event_type', sa.String(length=20), nullable=False),
        sa.Column('block_number', sa.BigInteger(), nullable=False),
        sa.Column('transaction_hash', sa.String(length=66), nullable=False),
        sa.Column('log_index', sa.Integer(), nullable=False),
        sa.Column('sender', sa.String(length=42), nullable=True),
        sa.Column('recipient', sa.String(length=42), nullable=True),
        sa.Column('amount0_in', sa.Float(), nullable=True),
        sa.Column('amount1_in', sa.Float(), nullable=True),
        sa.Column('amount0_out', sa.Float(), nullable=True),
        sa.Column('amount1_out', sa.Float(), nullable=True),
        sa.Column('estimated_usd', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('extra_data', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_events_id'), 'trade_events', ['id'], unique=False)
    op.create_index(op.f('ix_trade_events_pool_address'), 'trade_events', ['pool_address'], unique=False)
    
    # Create sentiment_scores table
    op.create_table('sentiment_scores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_address', sa.String(length=42), nullable=False),
        sa.Column('text_analyzed', sa.Text(), nullable=False),
        sa.Column('sentiment_score', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('model_version', sa.String(length=20), nullable=True),
        sa.Column('event_type', sa.String(length=20), nullable=True),
        sa.Column('block_number', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_id'), 'sentiment_scores', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_pool_address'), 'sentiment_scores', ['pool_address'], unique=False)
    
    # Create signals table
    op.create_table('signals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_address', sa.String(length=42), nullable=False),
        sa.Column('signal_type', sa.String(length=20), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('strategy_name', sa.String(length=50), nullable=True),
        sa.Column('signal_count', sa.Integer(), nullable=False),
        sa.Column('sentiment_score', sa.Integer(), nullable=True),
        sa.Column('sentiment_confidence', sa.Float(), nullable=True),
        sa.Column('related_events', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('triggered_at', sa.DateTime(), nullable=True),
        sa.Column('is_triggered', sa.Boolean(), nullable=True),
        sa.Column('extra_data', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_pool_address'), 'signals', ['pool_address'], unique=False)
    
    # Create alert_logs table
    op.create_table('alert_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pool_address', sa.String(length=42), nullable=False),
        sa.Column('signal_id', sa.Integer(), nullable=True),
        sa.Column('alert_type', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('delivery_method', sa.String(length=20), nullable=True),
        sa.Column('delivery_status', sa.String(length=20), nullable=True),
        sa.Column('delivery_response', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_index(op.f('ix_alert_logs_pool_address'), 'alert_logs', ['pool_address'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_pool_address'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_signals_pool_address'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sentiment_scores_pool_address'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_trade_events_pool_address'), table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_id'), table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index(op.f('ix_pools_address'), table_name='pools')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_table('pools')
    # ### end Alembic commands ###